spring.application.name=ms-rutina
server.port=8086

spring.datasource.url=jdbc:mysql://localhost:3306/ms-rutina
spring.datasource.username=root
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.flyway.enabled=true

jwt.secret=1234567890123456789012345678901234567890