spring:
  application:
    name: rutina
  jpa:
    show-sql: true

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
server:
  port: 8083
jwt:
  secret: 1234567890123456789012345678901234567890