spring.application.name=ms-eureka
server.port=8761
# Eureka Server no se registra a si mismo
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
# Configuracion util para ambiente academico/local
eureka.server.enable-self-preservation=false