spring.application.name=ms-gateway
server.port=8099

# Ruta 0: ms-auth (Puerto 8082)
spring.cloud.gateway.server.webmvc.routes[0].id=ms-auth
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/auth/**

# Ruta 1: ms-entrenador (Puerto 8093)
spring.cloud.gateway.server.webmvc.routes[1].id=ms-entrenador
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8093
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v1/entrenadores/**

# Ruta 2: ms-clase (Puerto 8094)
spring.cloud.gateway.server.webmvc.routes[2].id=ms-clase
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8094
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/v1/clases/**

# Ruta 3: ms-inscripcion-clase (Puerto 8092)
spring.cloud.gateway.server.webmvc.routes[3].id=ms-inscripcion-clase
spring.cloud.gateway.server.webmvc.routes[3].uri=http://localhost:8092
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/v1/inscripcion-clases/**