CREATE TABLE usuario (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL
);

CREATE TABLE refresh_token (
   id BIGINT AUTO_INCREMENT PRIMARY KEY,
   token VARCHAR(255) NOT NULL,
   username VARCHAR(50) NOT NULL,
   expiry_date DATETIME NOT NULL
);

