spring.application.name=ms-eureka
server.port=8761
# Eureka Server no se registra a sí mismo
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
# Configuración útil para ambiente académico/local
eureka.server.enable-self-preservation=false